server:
  port: 9200
spring:
  cloud:
    stream:
      # 实现手动ACK
      rabbit:
        bindings:
          sms_send_log_topic:
            consumer:
              acknowledgeMode: MANUAL
          report_update_topic:           # 修改es中的日志
            consumer:
              acknowledgeMode: MANUAL    # 手动ack
      bindings:
        #防止重复队列存在重复消息
        sms_send_log_topic:                # 队列名称
          group: search                    # 队列组名称
        report_update_topic:
          group: search
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    virtual-host: admin
    host: 192.168.194.140
es:
  hostandport: 192.168.194.140:9200
